# Generated by Django 5.2.3 on 2025-06-13 23:53

import board_photo.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PhotoBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("first_name", models.CharField(max_length=50, verbose_name="이름")),
                ("last_name", models.CharField(max_length=50, verbose_name="성")),
                ("email", models.EmailField(max_length=254, verbose_name="이메일")),
                ("password", models.CharField(max_length=128, verbose_name="비밀번호")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "image",
                    models.ImageField(
                        help_text="JPG, JPEG, PNG, GIF 파일만 업로드 가능합니다.",
                        upload_to=board_photo.models.upload_to_photo,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "gif"]
                            )
                        ],
                        verbose_name="이미지",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
            ],
            options={
                "verbose_name": "사진 게시판",
                "verbose_name_plural": "사진 게시판",
                "ordering": ["-created_at"],
            },
        ),
    ]
