# Generated by Django 5.2.3 on 2025-06-14 00:11

import board_routine.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board_routine", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="routineboard",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "읽걷쓰 루틴 챌린지",
                "verbose_name_plural": "읽걷쓰 루틴 챌린지",
            },
        ),
        migrations.AlterField(
            model_name="routineboard",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="JPG, JPEG, PNG, GIF 파일만 업로드 가능합니다.",
                null=True,
                upload_to=board_routine.models.upload_to_routine,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif"]
                    )
                ],
                verbose_name="읽걷쓰 루틴 챌린지 인증사진",
            ),
        ),
    ]
